-- MySQL Script generated by MySQL Workbench
-- Tue Sep 21 16:01:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemaCobranca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemaCobranca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaCobranca` DEFAULT CHARACTER SET utf8 ;
USE `sistemaCobranca` ;

-- -----------------------------------------------------
-- Table `sistemaCobranca`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaCobranca`.`cliente` (
  `idCliente` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valorPendente` FLOAT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idPessoa_UNIQUE` (`idCliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaCobranca`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaCobranca`.`pagamento` (
  `idPagamento` BIGINT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `cliente_idCliente` BIGINT NOT NULL,
  PRIMARY KEY (`idPagamento`, `cliente_idCliente`),
  UNIQUE INDEX `idPagamento_UNIQUE` (`idPagamento` ASC) VISIBLE,
  INDEX `fk_pagamento_cliente1_idx` (`cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `sistemaCobranca`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaCobranca`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaCobranca`.`compra` (
  `idCompra` BIGINT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `cliente_idCliente` BIGINT NOT NULL,
  PRIMARY KEY (`idCompra`, `cliente_idCliente`),
  UNIQUE INDEX `idCompra_UNIQUE` (`idCompra` ASC) VISIBLE,
  INDEX `fk_compra_cliente_idx` (`cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_compra_cliente`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `sistemaCobranca`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
